version: "3.6"
services:
  vpn:
    container_name: vpn
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN
    environment:
      DNS: 1.1.1.1,8.8.8.8
      TZ: ${TZ}
      PRIVATE_KEY: ${PRIVATE_KEY}
      NET_LOCAL: ${NET_LOCAL}
      QUERY: filters\[country_id\]=${COUNTRY_ID}&filters\[servers_groups\]\[identifier\]=${SERVER_TYPE}
    security_opt:
      - no-new-privileges:true
    ports:
      - 8081:80

  vpnchecker_vpn:
    container_name: vpnchecker_vpn
    build: .
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - ./src:/var/www/html

  vpnchecker_nonvpn:
    container_name: vpnchecker_nonvpn
    build: .
    restart: always
    depends_on:
      - vpnchecker_vpn
    ports:
      - 8082:80
    volumes:
      - ./src:/var/www/html
